version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - english-study-network

  english-study-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: english-study-server
    environment:
      - API_KEY=${API_KEY}
      - CACHE_DURATION=${CACHE_DURATION}
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - english-study-network
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  english-study-network:
    driver: bridge
